name: "Setup Node.js environment"
author: "Bart Venter <bartventer@outlook.com>"
branding:
  icon: "settings"
  color: "blue"
description: "Sets up a Node.js environment and caches dependencies"
inputs:
  node-version-file:
    description: "The file containing the Node.js version to use"
    required: true
    default: "package.json"
  cache:
    description: "The package manager to use for caching"
    required: true
    default: "yarn"
  cache-dependency-path:
    description: "The path to the lock file for caching"
    required: true
    default: "yarn.lock"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: "${{ inputs.node-version-file }}"
        cache: "${{ inputs.cache }}"
        cache-dependency-path: "${{ inputs.cache-dependency-path }}"
