ARG VARIANT="latest"
FROM archlinux:${VARIANT}

# Labels
LABEL org.opencontainers.image.source=https://github.com/bartventer/devcontainer-images
LABEL org.opencontainers.image.description="Arch Linux Development Container with common tools, including go, node, npm, yarn."
LABEL org.opencontainers.image.licenses=MIT