ARG VARIANT="latest"
FROM archlinux:${VARIANT}

# Labels
LABEL org.opencontainers.image.source=https://github.com/bartventer/devcontainer-images
LABEL org.opencontainers.image.description="Simple Arch Linux container with common tools installed"
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.authors="Bart Venter <bartventer@outlook.com>"