ARG VARIANT="latest"
FROM ghcr.io/bartventer/devcontainer-images/base-archlinux:${VARIANT}

LABEL org.opencontainers.image.title="Arch Linux Docker-in-Docker"
LABEL org.opencontainers.image.source="https://github.com/bartventer/devcontainer-images"
LABEL org.opencontainers.image.description="Arch Linux Docker-in-Docker image for development"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.authors="Bart Venter <bartventer@outlook.com>"