ARG VARIANT="latest"
FROM ghcr.io/bartventer/devcontainer-images/base-archlinux:${VARIANT}

LABEL org.opencontainers.image.title="Arch Linux Go"
LABEL org.opencontainers.image.source="https://github.com/bartventer/devcontainer-images"
LABEL org.opencontainers.image.description="Arch Linux container with Go installed"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.authors="Bart Venter <bartventer@outlook.com>"