name: Build

on:
  workflow_dispatch:
  schedule:
    # Every day at 00:00 UTC
    - cron: '0 0 * * *' 
  workflow_run: 
    workflows: ["Test"]
    branches: [master]
    types:
      - completed

jobs:
  release:
    if: ${{ contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name) || github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        image-name: ['base-archlinux']
    outputs:
      platforms: ${{ steps.platforms.outputs.platforms }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
            
      - uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: yarn global add @devcontainers/cli

      - name: Validate Metadata
        run: make IMAGE_NAME=${{ matrix.image-name }} validate

      - name: Get Platforms for ${{ matrix.image-name }}
        id: platforms
        run: |
          platforms=$(jq -r '.platforms | join(",")' src/${{ matrix.image-name }}/metadata.json)
          echo "platforms=$platforms" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ steps.platforms.outputs.platforms }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ steps.platforms.outputs.platforms }}
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build, Push and Release
        env:
          GH_ACTIONS_USERNAME: ${{ vars.GH_ACTIONS_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          scripts/build.sh ${{ matrix.image-name }}