name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      # To prevent the workflow from triggering itself
      - '!src/*/README.md'

jobs:
  validate:
    name: Validate Metadata
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image-name: ['archlinux']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn install
      - name: Validate Metadata
        run: make IMAGE_NAME=${{ matrix.image-name }} validate

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: validate
    permissions:
      contents: write
      packages: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        image-name: ['archlinux']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            src/${{ matrix.image-name }}
            doc
            scripts
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn install
      - name: Release
        env:
          GH_ACTIONS_USERNAME: ${{ vars.GH_ACTIONS_USERNAME }}
        run: |
          chmod +x scripts/release.sh
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $2}')
          scripts/release.sh ${{ matrix.image-name }} $REPO_NAME