name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      # To prevent the workflow from triggering itself
      - '!src/*/README.md'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        image-name: ['archlinux']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            src/${{ matrix.image-name }}
            doc
            scripts
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn install && yarn global add @devcontainers/cli
      - name: Validate Metadata
        run: make IMAGE_NAME=${{ matrix.image-name }} validate
      - name: Build, Push and Release
        env:
          GH_ACTIONS_USERNAME: ${{ vars.GH_ACTIONS_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x scripts/release.sh
          REPO_NAME=$(echo "${{ github.repository }}" | awk -F '/' '{print $2}')
          scripts/release.sh ${{ matrix.image-name }} $REPO_NAME